// This file is auto generated by GenerateUIText.cs. Please don't modify it by hand.
public enum UIText
{
		EMPTY_STRING,
		LANGUAGE,
		ENGLISH,
		CHINESE,
		START_GAME,
		LOGIN,
		CHAPTER_SELECT,
		ACHIEVEMENT,
		GLOBAL_LEADERBOARD
}
